services:
  - type: web
    name: walletguard-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: OG_PRIVATE_KEY
        sync: false
      - key: OG_EMAIL
        sync: false
      - key: OG_PASSWORD
        sync: false
      - key: FIREBASE_API_KEY
        sync: false
      - key: FIREBASE_AUTH_DOMAIN
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: FIREBASE_APP_ID
        sync: false
      - key: FIREBASE_DATABASE_URL
        sync: false
